//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WelcomeSOAPXMLTest.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IWelcomeSOAPXMLService")]
    public interface IWelcomeSOAPXMLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWelcomeSOAPXMLService/Welcome", ReplyAction="http://tempuri.org/IWelcomeSOAPXMLService/WelcomeResponse")]
        string Welcome(string yourName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWelcomeSOAPXMLService/Welcome", ReplyAction="http://tempuri.org/IWelcomeSOAPXMLService/WelcomeResponse")]
        System.Threading.Tasks.Task<string> WelcomeAsync(string yourName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWelcomeSOAPXMLService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IWelcomeSOAPXMLService/GetDataUsingDataContractResponse")]
        WelcomeSOAPXMLTest.ServiceReference.CompositeType GetDataUsingDataContract(WelcomeSOAPXMLTest.ServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWelcomeSOAPXMLService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IWelcomeSOAPXMLService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WelcomeSOAPXMLTest.ServiceReference.CompositeType> GetDataUsingDataContractAsync(WelcomeSOAPXMLTest.ServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWelcomeSOAPXMLServiceChannel : WelcomeSOAPXMLTest.ServiceReference.IWelcomeSOAPXMLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WelcomeSOAPXMLServiceClient : System.ServiceModel.ClientBase<WelcomeSOAPXMLTest.ServiceReference.IWelcomeSOAPXMLService>, WelcomeSOAPXMLTest.ServiceReference.IWelcomeSOAPXMLService {
        
        public WelcomeSOAPXMLServiceClient() {
        }
        
        public WelcomeSOAPXMLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WelcomeSOAPXMLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WelcomeSOAPXMLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WelcomeSOAPXMLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Welcome(string yourName) {
            return base.Channel.Welcome(yourName);
        }
        
        public System.Threading.Tasks.Task<string> WelcomeAsync(string yourName) {
            return base.Channel.WelcomeAsync(yourName);
        }
        
        public WelcomeSOAPXMLTest.ServiceReference.CompositeType GetDataUsingDataContract(WelcomeSOAPXMLTest.ServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WelcomeSOAPXMLTest.ServiceReference.CompositeType> GetDataUsingDataContractAsync(WelcomeSOAPXMLTest.ServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
